# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FIreBaseChatApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FIreBaseChatApp

pod 'Firebase/Core'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/Storage'
pod 'GoogleSignIn'


pod 'Fabric'
pod 'Answers'
end
